### ISSUE TITLE
Add ability to set session policies for assumed roles

### ISSUE THREAD

**Issue by iainelder** [connelldave/botocove#14]
The default OrganizationAccountAccessRole has the AdministratorAccess policy.

For collecting inventory, I need at most a read-only policy such as ReadOnlyAccess or SecurityAudit.

Botocove supports assuming other roles, but it doesn't help if we don't already have a role that attaches the read-only policies.

This could also be solved on botocove's side by adding options to set the Policy and PolicyArns parameters of [assume_role](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role).

https://github.com/connelldave/botocove/blob/77b015b703ae816d996119c6ac94a4b38c73909f/botocove/cove_decorator.py#L57-L59

I see that the RoleSessionName parameter gained support in a similar way.

* https://github.com/connelldave/botocove/issues/9 (issue)
* https://github.com/connelldave/botocove/pull/10 (pull request)

I think I would be able to contribute a PR for this functionality. My main doubt is about the test coverage. Can you give some guidance here?

**Comment by connelldave** [comment]
Sounds reasonable -we can't write any hugely meaningful tests since it's mainly just the API behaviour that changes. A test that uses new implemented arguments is mainly useful to catch regression or developer error so shouldn't be too tricky. Happy to review if you want to have a go.

Semi-related - I refactored the codebase without disrupting the user facing API on this branch. It drops some of the cruft like async.io loops and async funcs that don't really add much, and should hopefully allow progress bars. Feel free to check out https://github.com/connelldave/botocove/tree/progress_bar if you'd like to test. It'll be easy to port contributions to that change too if needs be.

**Comment by iainelder** [comment]
> Happy to review if you want to have a go.

Okay, thanks! I hope I can find time this week to implement it.

> I refactored ... should hopefully allow progress bars.

Glad to hear it :-) I'll copy the comment to #11.

**Comment by iainelder** [comment]
I submitted a pull request to solve this for the Policy parameter.

Let me know what you think.

When you're happy with it I can extend it to support the PolicyArns parameter too.

**Comment by connelldave** [comment]
Thanks for this Iain - now in 1.4.1 - it'd be great to hear more about your use case for it!

**Comment by iainelder** [comment]
@connelldave I'll update my aws-org-inventory tool soon to use a generic read-only session policy.

In more specialized code I would use a session policy that allows only the AWS API actions required by the function executed by botocove.

Say I need to retrieve the template for every instance of a named stack. I'd pass a function to botocove that calls boto3 method [CloudFormation.Client.get_template](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.get_template). I'd also pass a session policy that allows just the [`cloudformation:GetTemplate`](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awscloudformation.html) IAM action.
