### ISSUE TITLE
Add a progress bar for loading organization accounts

### ISSUE THREAD

**Issue by iainelder** [connelldave/botocove#51]
In a big org, loading the organization accounts takes several seconds.

In that time cove provides no feedback, so it's hard to know how much progress is being made.

If I know how big my org is and I can see how many accounts are loaded so far, I then have a better idea of how long to wait before my function starts running.

I think we can use tqdm for this by wrapping it around the iterator over the organization accounts.

**Comment by connelldave** [comment]
Yeah, I support this - should be a simple enough refactor of _get_active_org_accounts on cove_host_account?

My only input is I like the ugliest acid green for the bar colour :)

**Comment by iainelder** [comment]
> My only input is I like the ugliest acid green for the bar colour :)

Haha, yes! Bring it back :-)

**Comment by iainelder** [comment]
> My only input is I like the ugliest acid green for the bar colour :)

Haha, yes! Bring it back :-)

**Comment by iainelder** [comment]
Then problem with drawing a "bar" here is that we don't know the total number of accounts before calling ListAccounts.

We can either settle for a counter display, or we can hack it to display a bar.

If you don't set a total, you just get a counter.

![image](https://user-images.githubusercontent.com/5024311/208728526-d27a0c05-b9c9-40da-9f0e-4d84401a093a.png)

If you set a total of 5000, you see a green progress bar.

![image](https://user-images.githubusercontent.com/5024311/208726307-71be8bbd-321b-45c7-ae21-f98ca46ebe5c.png)

5000 is the maximum number of accounts, but it's almost never the real number of accounts.

In this case I think the bar for aesthetics' sake would actually be more confusing than helpful.

**Comment by iainelder** [comment]
> should be a simple enough refactor of _get_active_org_accounts on cove_host_account

I just realized it's not as simple as this in all cases.

If any of the target_ids and ignore_ids is an OU ID, then the OU needs to be listed recursively for accounts.

This part could take at least as long as the flat org-wide list.

So the progress of the OU-listing functions should be monitored in the same way.

I'm not sure how many extra spinners that implies.

* One per list operation
* One per ids list
* One per OU in each list

**Comment by connelldave** [comment]
I haven't touched tqdm for ages and I didn't feel like it was super friendly when I have, but I wonder if we can format it to be less ugly, and drop the percentage reporting - then have a bar and increment the endpoint with each iteration too? The outcome I'm thinking of is just a bar per operation (which can be named - OU-1, all accounts, etc), and instead of being relative it just gets longer... if someone has a 5k list to iterate through it'll just wrap a few lines or something?

I've never actually used the botocove TTY mode but I feel suprisingly strongly that it isn't too ugly :D

**Comment by iainelder** [comment]
I've abandoned the PR I started working on for this because the problem is harder than it first looked and because I'm no longer daily scraping 1000+ accounts :-)

I vote to close this for now.

**Comment by iainelder** [comment]
I realize I don't really want this feature.

Calling Organizations is an implementation detail that doesn't need to be exposed in the interface.

What I really want is faster feedback from Cove and faster overall execution.

We can do that with a queue and two threads. One thread collects the account list and writes account IDs to a queue. Another thread reads the account IDs from the queue and runs the user's function on it. This would allow the account processing to begin as soon as any account ID is known.

Easier said than done, but I think it's a better solution that complicating the user interface.

**Comment by connelldave** [comment]
I wrote that feature once and discarded it, because it introduces async problems into a sync threaded solution - the thinking being you end up with boto functions in flight when the 'what do I target' function is still resolving - probably not an issue most of the time, but it's a significant enough paradigm change I didn't feel comfortable with it. There's a timing optimisation problem too, of the queue chunk size and polling window being naturally a boto "get accounts ID" page size and how many threadpoolworkers are useful.

The behaviour you're looking for is relatively available to implement by just calling botocove in batches though - that immediately surfaces decisionmaking around batching/polling, and where the speed improvement kicks in versus establishing a new threadpool - but realistically if we're optimising for performance then this is in the realms of pushing everything into coroutines/asyncio. This is a good example of using botocove as a library to add opinionated extensions, imo.

On the original problem statement - I've been using Rich in some work ops scripts lately and a spinner solves well enough for me :) My thought was investigating splitting a setup.py flag for `botocove` and `botocove[notty|thin|slim|headless]` or similar, to avoid a tty dependency install being pulled into deps for people who don't want it.
